name: Deploy Website

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - name: Deploy source-code
        uses: appleboy/scp-action@master
        env:
          HOST: TEST_HOST
          USERNAME: USERNAME
          KEY: SSH_PRIVATE_KEY 
        with:
          source: "*"
          target: "/Projects/simplebank"